# **IP-1 FINAL PROJECT**

# **Title** : Car Brand Classification for AutoGenius

## **Source**: YBI Foundation GitHub (ML Project Ideas Repository)
## **Dataset**: Car Brand Classification for AutoGenius.

### Step 1 : Import library

In [17]:
import pandas as pd

### Step 2: Read Dataset

In [18]:
df = pd.read_csv('https://github.com/YBIFoundation/MLProjectIdeas/raw/main/Car%20Brand%20Classification%20for%20AutoGenius.csv')

In [19]:
df.head()

,Logo Shape,Headlight Design,Grille Size,Dominant Color,Wheel Base (cm),Body Length (cm),Car Brand
0,circle,sharp,medium,white,290.1,454.4,BMW
1,oval,sleek,medium,red,233.5,368.5,Hyundai
2,circle,sharp,large,blue,269.5,408.7,BMW
3,hexagon,sleek,medium,black,280.2,454.1,Hyundai
4,circle,round,medium,white,258.4,424.7,Toyota

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Logo Shape        1000 non-null   object
 1   Headlight Design  1000 non-null   object
 2   Grille Size       1000 non-null   object
 3   Dominant Color    1000 non-null   object
 4   Wheel Base (cm)   1000 non-null   float64
 5   Body Length (cm)  1000 non-null   float64
 6   Car Brand         1000 non-null   object
dtypes: float64(2), object(5)
memory usage: 54.8+ KB

In [21]:
df.describe()

       Wheel Base (cm)  Body Length (cm)
count      1000.000000        1000.00000
mean        261.699400         439.56720
std          19.693396          30.38667
min         199.400000         350.60000
25%         248.175000         418.87500
50%         261.650000         440.40000
75%         275.350000         460.42500
max         321.000000         526.50000

### Data Preprocessing (Label Encoding)

In [22]:
df.columns

Index(['Logo Shape', 'Headlight Design', 'Grille Size', 'Dominant Color',
       'Wheel Base (cm)', 'Body Length (cm)', 'Car Brand'],
      dtype='object')

In [23]:
# Check categories
df["Logo Shape"].value_counts()

df["Headlight Design"].value_counts()

df["Grille Size"].value_counts()

df["Dominant Color"].value_counts()

df["Car Brand"].value_counts()

Car Brand
BMW        178
Ford       177
Hyundai    174
Honda      164
Audi       155
Toyota     152
Name: count, dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder

brand_encoder = LabelEncoder()

df["Car Brand"] = brand_encoder.fit_transform(df["Car Brand"])

### Step 3: Define y and X

In [25]:
y = df["Car Brand"]
X = df[["Logo Shape","Headlight Design","Grille Size",
    "Dominant Color","Wheel Base (cm)","Body Length (cm)"]]
X = pd.get_dummies(X, dtype=int)

### Step 4 : Train Test Split

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2529)

### Step 5 : Select Model

In [27]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=2529)

### Step 6 : Train Model

In [28]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=2529)

### Step 7 : Prediction

In [29]:
y_pred = model.predict(X_test)
y_pred

array([1, 3, 3, 5, 2, 3, 5, 1, 1, 0, 2, 2, 3, 2, 3, 4, 5, 3, 2, 4, 5, 2,
       1, 2, 0, 0, 5, 3, 3, 5, 2, 1, 0, 0, 5, 5, 1, 3, 4, 0, 0, 5, 2, 1,
       1, 4, 4, 2, 4, 5, 2, 2, 4, 2, 1, 1, 1, 0, 2, 2, 2, 0, 0, 5, 3, 4,
       0, 4, 3, 4, 4, 2, 0, 0, 4, 4, 2, 5, 3, 0, 0, 1, 0, 4, 2, 0, 5, 2,
       2, 4, 2, 3, 1, 1, 3, 0, 0, 4, 0, 5, 5, 2, 0, 0, 1, 0, 3, 0, 1, 2,
       3, 4, 4, 2, 2, 4, 3, 0, 1, 5, 1, 3, 3, 1, 5, 5, 2, 3, 5, 5, 2, 4,
       4, 3, 5, 3, 2, 4, 2, 2, 1, 0, 5, 4, 0, 1, 3, 5, 1, 3, 4, 0, 1, 2,
       0, 4, 1, 0, 1, 1, 4, 0, 4, 1, 4, 2, 1, 4, 2, 2, 0, 2, 2, 3, 1, 4,
       3, 5, 0, 3, 3, 3, 0, 5, 1, 2, 3, 2, 4, 3, 5, 5, 0, 1, 4, 1, 2, 2,
       4, 1])

### Step 8 : Evaluate

In [32]:
from sklearn.metrics import accuracy_score
print("Accuracy Score")
print(accuracy_score(y_test, y_pred))

Accuracy Score
0.17

In [33]:
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

           0       0.14      0.21      0.17        24
           1       0.18      0.18      0.18        33
           2       0.17      0.17      0.17        42
           3       0.23      0.21      0.22        33
           4       0.09      0.08      0.08        38
           5       0.22      0.20      0.21        30

    accuracy                           0.17       200
   macro avg       0.17      0.17      0.17       200
weighted avg       0.17      0.17      0.17       200

## **Conclusion**
This project successfully implemented a Machine Learning model for Car Brand Classification using the Random Forest Classifier. The complete machine learning workflow was followed, including data preprocessing, label encoding, feature selection, train-test splitting, model training, prediction, and evaluation. This project demonstrates the practical application of classification techniques using machine learning.

## **Model Performance Analysis and Reason**
The model achieved a relatively low accuracy because the available features provide limited information to clearly distinguish between different car brands. Multiple classification algorithms, including Decision Tree, KNN, Logistic Regression, Naive Bayes, and Random Forest, were tested and produced similar results. This indicates that the implementation is correct, while the dataset characteristics have a greater impact on the overall model performance.

## **PROJECT REPORT**

**Title** : Car Brand Classification for AutoGenius

**Dataset** **Source** : YBI Foundation GitHub (ML Project Ideas Repository)

**Project Type** : Classification using Machine learning

**Submitted By** : BHARAT SONI



**Purpose** :

To build a machine learning model that classifies car brands based on their design and physical features using Machine learning techniques.

**Objective** :

To understand and implement the complete machine learning classification workflow, including data preprocessing, feature selection, model training, prediction, and evaluation using the Random Forest Classifier.

**Dataset :**

The dataset contains approximately 1000 records with six input features (Logo Shape, Headlight Design, Grille Size, Dominant Color, Wheel Base, and Body Length) and one target variable (Car Brand).

**Workflow :**

**Purpose of Each Step :**

**Step 1**: **Import Library**

To import the required Python libraries that are used for data preprocessing, model building, prediction, and evaluation.

**Step 2**: **Read Dataset**

To load the dataset into a Pandas DataFrame so that it can be explored and used for machine learning.

**Data Preprocessing (Label Encoding)**

To convert categorical (text) values into numerical values, enabling the machine learning model to process the data correctly.

**Step 3: Define X and y**

To separate the input features (X) from the target variable (y) that the model will learn to predict.

**Step 4 : Train-Test Split**

Splits the dataset into training (80%) and testing (20%) sets to evaluate the model.

**Step 5: Select Model**

To choose the Random Forest Classifier as the machine learning algorithm for solving the classification problem.

**Step 6: Train Model**

To train the Random Forest model using the training dataset so that it can learn patterns and relationships in the data.

**Step 7: Prediction**

To use the trained model to predict the car brand for the testing dataset based on the learned patterns.

**Step 8: Evaluation**

To evaluate the model's performance using Accuracy Score and Classification Report to measure the quality of its predictions.

**Expected Outcome :**

The project aims to build a machine learning model capable of predicting the car brand based on the given vehicle features. It also demonstrates the practical implementation of a complete classification workflow using supervised machine learning.